backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "static/images/uploads/"
public_folder: "static/images/uploads/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    fields:
      - { name: "title", label: "Title", required: true }
      - {
          name: "thumbnail",
          label: "Featured Image",
          widget: "image",
          required: true,
        }
      - { name: "desc", label: "Description", required: true }
      - { name: "body", label: "Body", widget: "markdown", required: true }
      - { name: "category", label: "Category", widget: "List", required: true }
      - { name: "tags", label: "Tags", widget: "List", required: true }
      - {
          name: date,
          label: Date,
          widget: "date",
          format: "DD/MM/YYYY",
          required: true,
        }
