backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: blog
    label: Blog
    folder: blogs
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: desc, label: Description }
      - { name: body, label: Body, widget: markdown }
